let data = [
  { countryName: "Afghanistan", awailable: false },
  { countryName: "Åland Islands", awailable: false },
  { countryName: "Albania", awailable: false },
  { countryName: "Algeria", awailable: false },
  { countryName: "American Samoa", awailable: false },
  { countryName: "Andorra", awailable: false },
  { countryName: "Angola", awailable: false },
  { countryName: "Anguilla", awailable: false },
  { countryName: "Antarctica", awailable: false },
  { countryName: "Antigua and Barbuda", awailable: false },
  { countryName: "Argentina", awailable: false },
  { countryName: "Armenia", awailable: false },
  { countryName: "Aruba", awailable: false },
  { countryName: "Australia", awailable: false },
  { countryName: "Austria", awailable: false },
  { countryName: "Azerbaijan", awailable: false },
  { countryName: "Bahamas", awailable: false },
  { countryName: "Bahrain", awailable: false },
  { countryName: "Bangladesh", awailable: false },
  { countryName: "Barbados", awailable: false },
  { countryName: "Belarus", awailable: false },
  { countryName: "Belgium", awailable: false },
  { countryName: "Belize", awailable: false },
  { countryName: "Benin", awailable: false },
  { countryName: "Bermuda", awailable: false },
  { countryName: "Bhutan", awailable: false },
  { countryName: "Bolivia", awailable: false },
  { countryName: "Bosnia and Herzegovina", awailable: false },
  { countryName: "Botswana", awailable: false },
  { countryName: "Bouvet Island", awailable: false },
  { countryName: "Brazil", awailable: false },
  { countryName: "British Indian Ocean Territory", awailable: false },
  { countryName: "Brunei Darussalam", awailable: false },
  { countryName: "Bulgaria", awailable: false },
  { countryName: "Burkina Faso", awailable: false },
  { countryName: "Burundi", awailable: false },
  { countryName: "Cambodia", awailable: false },
  { countryName: "Cameroon", awailable: false },
  { countryName: "Canada", awailable: false },
  { countryName: "Cape Verde", awailable: false },
  { countryName: "Cayman Islands", awailable: false },
  { countryName: "Central African Republic", awailable: false },
  { countryName: "Chad", awailable: false },
  { countryName: "Chile", awailable: false },
  { countryName: "China", awailable: false },
  { countryName: "Christmas Island", awailable: false },
  { countryName: "Cocos (Keeling) Islands", awailable: false },
  { countryName: "Colombia", awailable: false },
  { countryName: "Comoros", awailable: false },
  { countryName: "Congo", awailable: false },
  { countryName: "Congo, The Democratic Republic of The", awailable: false },
  { countryName: "Cook Islands", awailable: false },
  { countryName: "Costa Rica", awailable: false },
  { countryName: "Cote D'ivoire", awailable: false },
  { countryName: "Croatia", awailable: false },
  { countryName: "Cuba", awailable: false },
  { countryName: "Cyprus", awailable: false },
  { countryName: "Czech Republic", awailable: false },
  { countryName: "Denmark", awailable: false },
  { countryName: "Djibouti", awailable: false },
  { countryName: "Dominica", awailable: false },
  { countryName: "Dominican Republic", awailable: false },
  { countryName: "Ecuador", awailable: false },
  { countryName: "Egypt", awailable: false },
  { countryName: "El Salvador", awailable: false },
  { countryName: "Equatorial Guinea", awailable: false },
  { countryName: "Eritrea", awailable: false },
  { countryName: "Estonia", awailable: false },
  { countryName: "Ethiopia", awailable: false },
  { countryName: "Falkland Islands (Malvinas)", awailable: false },
  { countryName: "Faroe Islands", awailable: false },
  { countryName: "Fiji", awailable: false },
  { countryName: "Finland", awailable: false },
  { countryName: "France", awailable: false },
  { countryName: "French Guiana", awailable: false },
  { countryName: "French Polynesia", awailable: false },
  { countryName: "French Southern Territories", awailable: false },
  { countryName: "Gabon", awailable: false },
  { countryName: "Gambia", awailable: false },
  { countryName: "Georgia", awailable: false },
  { countryName: "Germany", awailable: false },
  { countryName: "Ghana", awailable: false },
  { countryName: "Gibraltar", awailable: false },
  { countryName: "Greece", awailable: false },
  { countryName: "Greenland", awailable: false },
  { countryName: "Grenada", awailable: false },
  { countryName: "Guadeloupe", awailable: false },
  { countryName: "Guam", awailable: false },
  { countryName: "Guatemala", awailable: false },
  { countryName: "Guernsey", awailable: false },
  { countryName: "Guinea", awailable: false },
  { countryName: "Guinea-bissau", awailable: false },
  { countryName: "Guyana", awailable: false },
  { countryName: "Haiti", awailable: false },
  { countryName: "Heard Island and Mcdonald Islands", awailable: false },
  { countryName: "Holy See (Vatican City State)", awailable: false },
  { countryName: "Honduras", awailable: false },
  { countryName: "Hong Kong", awailable: false },
  { countryName: "Hungary", awailable: false },
  { countryName: "Iceland", awailable: false },
  { countryName: "India", awailable: true },
  { countryName: "Indonesia", awailable: false },
  { countryName: "Iran, Islamic Republic of", awailable: false },
  { countryName: "Iraq", awailable: false },
  { countryName: "Ireland", awailable: false },
  { countryName: "Isle of Man", awailable: false },
  { countryName: "Israel", awailable: false },
  { countryName: "Italy", awailable: false },
  { countryName: "Jamaica", awailable: false },
  { countryName: "Japan", awailable: false },
  { countryName: "Jersey", awailable: false },
  { countryName: "Jordan", awailable: false },
  { countryName: "Kazakhstan", awailable: false },
  { countryName: "Kenya", awailable: false },
  { countryName: "Kiribati", awailable: false },
  { countryName: "Korea, Democratic People's Republic of", awailable: false },
  { countryName: "Korea, Republic of", awailable: false },
  { countryName: "Kuwait", awailable: false },
  { countryName: "Kyrgyzstan", awailable: false },
  { countryName: "Lao People's Democratic Republic", awailable: false },
  { countryName: "Latvia", awailable: false },
  { countryName: "Lebanon", awailable: false },
  { countryName: "Lesotho", awailable: false },
  { countryName: "Liberia", awailable: false },
  { countryName: "Libyan Arab Jamahiriya", awailable: false },
  { countryName: "Liechtenstein", awailable: false },
  { countryName: "Lithuania", awailable: false },
  { countryName: "Luxembourg", awailable: false },
  { countryName: "Macao", awailable: false },
  {
    countryName: "Macedonia, The Former Yugoslav Republic of",
    awailable: false,
  },
  { countryName: "Madagascar", awailable: false },
  { countryName: "Malawi", awailable: false },
  { countryName: "Malaysia", awailable: false },
  { countryName: "Maldives", awailable: false },
  { countryName: "Mali", awailable: false },
  { countryName: "Malta", awailable: false },
  { countryName: "Marshall Islands", awailable: false },
  { countryName: "Martinique", awailable: false },
  { countryName: "Mauritania", awailable: false },
  { countryName: "Mauritius", awailable: false },
  { countryName: "Mayotte", awailable: false },
  { countryName: "Mexico", awailable: false },
  { countryName: "Micronesia, Federated States of", awailable: false },
  { countryName: "Moldova, Republic of", awailable: false },
  { countryName: "Monaco", awailable: false },
  { countryName: "Mongolia", awailable: false },
  { countryName: "Montenegro", awailable: false },
  { countryName: "Montserrat", awailable: false },
  { countryName: "Morocco", awailable: false },
  { countryName: "Mozambique", awailable: false },
  { countryName: "Myanmar", awailable: false },
  { countryName: "Namibia", awailable: false },
  { countryName: "Nauru", awailable: false },
  { countryName: "Nepal", awailable: false },
  { countryName: "Netherlands", awailable: false },
  { countryName: "Netherlands Antilles", awailable: false },
  { countryName: "New Caledonia", awailable: false },
  { countryName: "New Zealand", awailable: false },
  { countryName: "Nicaragua", awailable: false },
  { countryName: "Niger", awailable: false },
  { countryName: "Nigeria", awailable: false },
  { countryName: "Niue", awailable: false },
  { countryName: "Norfolk Island", awailable: false },
  { countryName: "Northern Mariana Islands", awailable: false },
  { countryName: "Norway", awailable: false },
  { countryName: "Oman", awailable: false },
  { countryName: "Pakistan", awailable: false },
  { countryName: "Palau", awailable: false },
  { countryName: "Palestinian Territory, Occupied", awailable: false },
  { countryName: "Panama", awailable: false },
  { countryName: "Papua New Guinea", awailable: false },
  { countryName: "Paraguay", awailable: false },
  { countryName: "Peru", awailable: false },
  { countryName: "Philippines", awailable: false },
  { countryName: "Pitcairn", awailable: false },
  { countryName: "Poland", awailable: false },
  { countryName: "Portugal", awailable: false },
  { countryName: "Puerto Rico", awailable: false },
  { countryName: "Qatar", awailable: false },
  { countryName: "Reunion", awailable: false },
  { countryName: "Romania", awailable: false },
  { countryName: "Russian Federation", awailable: false },
  { countryName: "Rwanda", awailable: false },
  { countryName: "Saint Helena", awailable: false },
  { countryName: "Saint Kitts and Nevis", awailable: false },
  { countryName: "Saint Lucia", awailable: false },
  { countryName: "Saint Pierre and Miquelon", awailable: false },
  { countryName: "Saint Vincent and The Grenadines", awailable: false },
  { countryName: "Samoa", awailable: false },
  { countryName: "San Marino", awailable: false },
  { countryName: "Sao Tome and Principe", awailable: false },
  { countryName: "Saudi Arabia", awailable: false },
  { countryName: "Senegal", awailable: false },
  { countryName: "Serbia", awailable: false },
  { countryName: "Seychelles", awailable: false },
  { countryName: "Sierra Leone", awailable: false },
  { countryName: "Singapore", awailable: false },
  { countryName: "Slovakia", awailable: false },
  { countryName: "Slovenia", awailable: false },
  { countryName: "Solomon Islands", awailable: false },
  { countryName: "Somalia", awailable: false },
  { countryName: "South Africa", awailable: false },
  {
    countryName: "South Georgia and The South Sandwich Islands",
    awailable: false,
  },
  { countryName: "Spain", awailable: false },
  { countryName: "Sri Lanka", awailable: false },
  { countryName: "Sudan", awailable: false },
  { countryName: "SuricountryName", awailable: false },
  { countryName: "Svalbard and Jan Mayen", awailable: false },
  { countryName: "Swaziland", awailable: false },
  { countryName: "Sweden", awailable: false },
  { countryName: "Switzerland", awailable: false },
  { countryName: "Syrian Arab Republic", awailable: false },
  { countryName: "Taiwan (ROC)", awailable: false },
  { countryName: "Tajikistan", awailable: false },
  { countryName: "Tanzania, United Republic of", awailable: false },
  { countryName: "Thailand", awailable: false },
  { countryName: "Timor-leste", awailable: false },
  { countryName: "Togo", awailable: false },
  { countryName: "Tokelau", awailable: false },
  { countryName: "Tonga", awailable: false },
  { countryName: "Trinidad and Tobago", awailable: false },
  { countryName: "Tunisia", awailable: false },
  { countryName: "Turkey", awailable: false },
  { countryName: "Turkmenistan", awailable: false },
  { countryName: "Turks and Caicos Islands", awailable: false },
  { countryName: "Tuvalu", awailable: false },
  { countryName: "Uganda", awailable: false },
  { countryName: "Ukraine", awailable: false },
  { countryName: "United Arab Emirates", awailable: false },
  { countryName: "United Kingdom", awailable: false },
  { countryName: "United States", awailable: true },
  { countryName: "United States Minor Outlying Islands", awailable: false },
  { countryName: "Uruguay", awailable: false },
  { countryName: "Uzbekistan", awailable: false },
  { countryName: "Vanuatu", awailable: false },
  { countryName: "Venezuela", awailable: false },
  { countryName: "Viet Nam", awailable: false },
  { countryName: "Virgin Islands, British", awailable: false },
  { countryName: "Virgin Islands, U.S.", awailable: false },
  { countryName: "Wallis and Futuna", awailable: false },
  { countryName: "Western Sahara", awailable: false },
  { countryName: "Yemen", awailable: false },
  { countryName: "Zambia", awailable: false },
  { countryName: "Zimbabwe", awailable: false },
];

const Country = require("../../auth/database/mongoModels/details/countryList.model");

module.exports = async function addCountry(req, res) {
  Country.insertMany(data)
    .then((cntry) => {
      console.log("data inserted => ", cntry);
      return res.send("Done");
    })
    .catch((error) => {
      console.log("Error =>", error);
      return res.status(500).send("Internal server error");
    });
};
