export const ActionTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  STORE_LOGIN: "STORE_LOGIN",
  STORE_LOGOUT: "STORE_LOGOUT",

  ADD_TO_CART: "ADD_TO_CART",
  INCREASE_PRODUCT: "INCREASE_PRODUCT",
  DECREASE_PRODUCT: "DECREASE_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",

  PROCEED_TO_BUY_FROM_CART: "PROCEED_TO_BUY_FROM_CART",
  PROCEED_TO_BUY_PRODUCT: "PROCEED_TO_BUY_PRODUCT",
  BUY_PRODUCT: "BUY_PRODUCT",
};
